### ISSUE TITLE
unable to call npm start

### ISSUE THREAD

**Issue by Kola50011** [PRIArobotics/hedgehog-ide#72]
Hey, I am sadly unable to start the hedgehog ide. I followed the installation instructions for building from source.

$ npm start

> hedgehog-ide@1.3.0 start /home/void/workspace/hedgehog-ide
> node build/src/server/server.js

  _   _          _            _                   ___ ____  _____ 
 | | | | ___  __| | __ _  ___| |__   ___   __ _  |_ _|  _ \| ____|
 | |_| |/ _ \/ _` |/ _` |/ _ \ '_ \ / _ \ / _` |  | || | | |  _|  
 |  _  |  __/ (_| | (_| |  __/ | | | (_) | (_| |  | || |_| | |___ 
 |_| |_|\___|\__,_|\__, |\___|_| |_|\___/ \__, | |___|____/|_____|
                   |___/                  |___/                   
(node:1781) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: validate OR verify function is required!
    at Object.internals.implementation [as jwt] (/home/void/workspace/hedgehog-ide/node_modules/hapi-auth-jwt2/lib/index.js:66:3)
    at module.exports.internals.Auth._strategy (/home/void/workspace/hedgehog-ide/node_modules/hapi/lib/auth.js:52:47)
    at Object.<anonymous> (/home/void/workspace/hedgehog-ide/build/src/server/server.js:115:29)
    at step (/home/void/workspace/hedgehog-ide/build/src/server/server.js:32:23)
    at Object.next (/home/void/workspace/hedgehog-ide/build/src/server/server.js:13:53)
    at fulfilled (/home/void/workspace/hedgehog-ide/build/src/server/server.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
(node:1781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by trestoa** [comment]
Hi,

thanks for submitting this issue!
Apparently the node module we use for authentication (`hapi-auth-jwt2`) changed the property name for the validate function which was not adapted when we updated the dependency. I fixed the property name and the IDE should start properly now. 

I will close this issue for now, it you experience any further problems, please feel free to reopen it.
